"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Adrián Estrada Marroquín and Valentina Treviño this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: vt6738
UT EID 2: ae28294
"""


def rail_fence_encode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: returns a single string that is encoded with
        rail fence algorithm
    """
    if key <= 1 or key >= len(string):
        return string

    rail = ['' for _ in range(key)]
    row, direction = 0, 1

    for char in string:
        rail[row] += char
        row += direction
        if row == 0 or row == key - 1:
            direction *= -1

    return ''.join(rail)


def rail_fence_decode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: function returns a single string that is decoded with
        rail fence algorithm
    """
    if key <= 1 or key >= len(string):
        return string

    n = len(string)
    matrix = [['' for _ in range(n)] for _ in range(key)]

    row, direction = 0, 1
    for col in range(n):
        matrix[row][col] = '*'
        row += direction
        if row == 0 or row == key - 1:
            direction *= -1

    idx = 0
    for i in range(key):
        for j in range(n):
            if matrix[i][j] == '*' and idx < n:
                matrix[i][j] = string[idx]
                idx += 1

    result = ''
    row, direction = 0, 1
    for col in range(n):
        result += matrix[row][col]
        row += direction
        if row == 0 or row == key - 1:
            direction *= -1

    return result


def filter_string(string):
    """
    pre: string is a string of characters
    post: function converts all characters to lower case and then
        removes all digits, punctuation marks, and spaces. It
        returns a single string with only lower case characters
    """
    return ''.join([c for c in string.lower() if c.isalpha()])


def encode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the plain text
    post: function returns a single character encoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    return chr(((ord(p) - ord('a')) + (ord(s) - ord('a'))) % 26 + ord('a'))


def decode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the encrypted text
    post: function returns a single character decoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    return chr(((ord(s) - ord(p) + 26) % 26) + ord('a'))


def vigenere_encode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is encoded with
        Vigenere algorithm
    """
    clean = filter_string(string)
    phrase = phrase.lower()
    return ''.join(encode_character(phrase[i % len(phrase)], c) for i, c in enumerate(clean))


def vigenere_decode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is decoded with
        Vigenere algorithm
    """
    string = filter_string(string)
    phrase = phrase.lower()
    return ''.join(decode_character(phrase[i % len(phrase)], c) for i, c in enumerate(string))


def main():
    """Main function that reads stdin and runs each cipher"""
    plain_text = input().strip()
    rf_key_encode = int(input().strip())

    print("Rail Fence Cipher\n")
    print(f"Plain Text: {plain_text}")
    print(f"Key: {rf_key_encode}")
    rf_encoded = rail_fence_encode(plain_text, rf_key_encode)
    print(f"Encoded Text: {rf_encoded}\n")

    rf_encoded_input = input().strip()
    rf_key_decode = int(input().strip())
    print(f"Encoded Text: {rf_encoded_input}")
    print(f"Enter Key: {rf_key_decode}")
    rf_decoded = rail_fence_decode(rf_encoded_input, rf_key_decode)
    print(f"Decoded Text: {rf_decoded}\n")

    print("Vigenere Cipher\n")
    plain_vig = input().strip()
    passphrase = input().strip()
    print(f"Plain Text: {plain_vig}")
    print(f"Pass Phrase: {passphrase}")
    vig_encoded = vigenere_encode(plain_vig, passphrase)
    print(f"Encoded Text: {vig_encoded}\n")

    vig_encoded_input = input().strip()
    passphrase2 = input().strip()
    print(f"Encoded Text: {vig_encoded_input}")
    print(f"Pass Phrase: {passphrase2}")
    vig_decoded = vigenere_decode(vig_encoded_input, passphrase2)
    print(f"Decoded Text: {vig_decoded}")


# Do NOT modify the following code.
if __name__ == "__main__":
    main()
